name: text_wrap_auto_size
description: Wraps text and auto sizes it dynamically with respect to the given dimensions. 
issue_tracker: https://github.com/xErik/text_wrap_auto_size/issues
repository: https://github.com/xErik/text_wrap_auto_size

version: 1.1.1

# publish_to: none

environment:
  # sdk: '>=2.19.6 <4.0.0'
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # hyphenatorx: 
  #   path: ../hyphenatorx
  hyphenatorx: ^1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
 