name: text_wrap_auto_size
description: Wraps text and auto sizes it dynamically with respect to the given space. 
issues: https://github.com/xErik/text_wrap_auto_size/issues
repository: https://github.com/xErik/text_wrap_auto_size

version: 1.0.7+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
 